#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 114
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  aux_sym_markup_leading_whitespace_token1 = 1,
  aux_sym_newline_token1 = 2,
  aux_sym_whitespace_token1 = 3,
  aux_sym_word_token1 = 4,
  aux_sym_special_token1 = 5,
  anon_sym_STAR = 6,
  anon_sym__ = 7,
  sym_last_token_non_word = 8,
  sym_last_token_word = 9,
  sym_strong_open = 10,
  sym_strong_close = 11,
  sym_italic_open = 12,
  sym_italic_close = 13,
  sym_heading_prefix = 14,
  sym_equalsigns = 15,
  sym___error_canary = 16,
  sym_markup_block = 17,
  sym__markup_content = 18,
  sym_markup_leading_whitespace = 19,
  sym_newline = 20,
  sym_whitespace = 21,
  sym_word = 22,
  sym_special = 23,
  sym_star = 24,
  sym_underscore = 25,
  sym_strong = 26,
  sym_strong_content = 27,
  sym_italic = 28,
  sym_italic_content = 29,
  sym_heading = 30,
  sym_heading_whitespace = 31,
  sym_heading_content = 32,
  sym_line = 33,
  sym_line_content = 34,
  aux_sym_markup_block_repeat1 = 35,
  aux_sym_markup_leading_whitespace_repeat1 = 36,
  aux_sym_whitespace_repeat1 = 37,
  aux_sym_special_repeat1 = 38,
  aux_sym_strong_content_repeat1 = 39,
  aux_sym_italic_content_repeat1 = 40,
  aux_sym_heading_content_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_markup_leading_whitespace_token1] = "markup_leading_whitespace_token1",
  [aux_sym_newline_token1] = "newline_token1",
  [aux_sym_whitespace_token1] = "whitespace_token1",
  [aux_sym_word_token1] = "word_token1",
  [aux_sym_special_token1] = "special_token1",
  [anon_sym_STAR] = "*",
  [anon_sym__] = "_",
  [sym_last_token_non_word] = "last_token_non_word",
  [sym_last_token_word] = "last_token_word",
  [sym_strong_open] = "strong_open",
  [sym_strong_close] = "strong_close",
  [sym_italic_open] = "italic_open",
  [sym_italic_close] = "italic_close",
  [sym_heading_prefix] = "heading_prefix",
  [sym_equalsigns] = "equalsigns",
  [sym___error_canary] = "__error_canary",
  [sym_markup_block] = "markup_block",
  [sym__markup_content] = "_markup_content",
  [sym_markup_leading_whitespace] = "markup_leading_whitespace",
  [sym_newline] = "newline",
  [sym_whitespace] = "whitespace",
  [sym_word] = "word",
  [sym_special] = "special",
  [sym_star] = "star",
  [sym_underscore] = "underscore",
  [sym_strong] = "strong",
  [sym_strong_content] = "strong_content",
  [sym_italic] = "italic",
  [sym_italic_content] = "italic_content",
  [sym_heading] = "heading",
  [sym_heading_whitespace] = "heading_whitespace",
  [sym_heading_content] = "heading_content",
  [sym_line] = "line",
  [sym_line_content] = "line_content",
  [aux_sym_markup_block_repeat1] = "markup_block_repeat1",
  [aux_sym_markup_leading_whitespace_repeat1] = "markup_leading_whitespace_repeat1",
  [aux_sym_whitespace_repeat1] = "whitespace_repeat1",
  [aux_sym_special_repeat1] = "special_repeat1",
  [aux_sym_strong_content_repeat1] = "strong_content_repeat1",
  [aux_sym_italic_content_repeat1] = "italic_content_repeat1",
  [aux_sym_heading_content_repeat1] = "heading_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_markup_leading_whitespace_token1] = aux_sym_markup_leading_whitespace_token1,
  [aux_sym_newline_token1] = aux_sym_newline_token1,
  [aux_sym_whitespace_token1] = aux_sym_whitespace_token1,
  [aux_sym_word_token1] = aux_sym_word_token1,
  [aux_sym_special_token1] = aux_sym_special_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym__] = anon_sym__,
  [sym_last_token_non_word] = sym_last_token_non_word,
  [sym_last_token_word] = sym_last_token_word,
  [sym_strong_open] = sym_strong_open,
  [sym_strong_close] = sym_strong_close,
  [sym_italic_open] = sym_italic_open,
  [sym_italic_close] = sym_italic_close,
  [sym_heading_prefix] = sym_heading_prefix,
  [sym_equalsigns] = sym_equalsigns,
  [sym___error_canary] = sym___error_canary,
  [sym_markup_block] = sym_markup_block,
  [sym__markup_content] = sym__markup_content,
  [sym_markup_leading_whitespace] = sym_markup_leading_whitespace,
  [sym_newline] = sym_newline,
  [sym_whitespace] = sym_whitespace,
  [sym_word] = sym_word,
  [sym_special] = sym_special,
  [sym_star] = sym_star,
  [sym_underscore] = sym_underscore,
  [sym_strong] = sym_strong,
  [sym_strong_content] = sym_strong_content,
  [sym_italic] = sym_italic,
  [sym_italic_content] = sym_italic_content,
  [sym_heading] = sym_heading,
  [sym_heading_whitespace] = sym_heading_whitespace,
  [sym_heading_content] = sym_heading_content,
  [sym_line] = sym_line,
  [sym_line_content] = sym_line_content,
  [aux_sym_markup_block_repeat1] = aux_sym_markup_block_repeat1,
  [aux_sym_markup_leading_whitespace_repeat1] = aux_sym_markup_leading_whitespace_repeat1,
  [aux_sym_whitespace_repeat1] = aux_sym_whitespace_repeat1,
  [aux_sym_special_repeat1] = aux_sym_special_repeat1,
  [aux_sym_strong_content_repeat1] = aux_sym_strong_content_repeat1,
  [aux_sym_italic_content_repeat1] = aux_sym_italic_content_repeat1,
  [aux_sym_heading_content_repeat1] = aux_sym_heading_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_markup_leading_whitespace_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_newline_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_whitespace_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_special_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [sym_last_token_non_word] = {
    .visible = true,
    .named = true,
  },
  [sym_last_token_word] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_open] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_close] = {
    .visible = true,
    .named = true,
  },
  [sym_italic_open] = {
    .visible = true,
    .named = true,
  },
  [sym_italic_close] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_equalsigns] = {
    .visible = true,
    .named = true,
  },
  [sym___error_canary] = {
    .visible = false,
    .named = true,
  },
  [sym_markup_block] = {
    .visible = true,
    .named = true,
  },
  [sym__markup_content] = {
    .visible = false,
    .named = true,
  },
  [sym_markup_leading_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_special] = {
    .visible = true,
    .named = true,
  },
  [sym_star] = {
    .visible = true,
    .named = true,
  },
  [sym_underscore] = {
    .visible = true,
    .named = true,
  },
  [sym_strong] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_content] = {
    .visible = true,
    .named = true,
  },
  [sym_italic] = {
    .visible = true,
    .named = true,
  },
  [sym_italic_content] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_content] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_line_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_markup_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markup_leading_whitespace_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_whitespace_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_special_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_strong_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_italic_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 8,
  [10] = 7,
  [11] = 11,
  [12] = 12,
  [13] = 11,
  [14] = 12,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 33,
  [40] = 37,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 48,
  [50] = 44,
  [51] = 32,
  [52] = 41,
  [53] = 47,
  [54] = 25,
  [55] = 25,
  [56] = 42,
  [57] = 45,
  [58] = 58,
  [59] = 48,
  [60] = 34,
  [61] = 35,
  [62] = 45,
  [63] = 41,
  [64] = 32,
  [65] = 44,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 36,
  [70] = 58,
  [71] = 29,
  [72] = 72,
  [73] = 38,
  [74] = 72,
  [75] = 29,
  [76] = 68,
  [77] = 67,
  [78] = 66,
  [79] = 37,
  [80] = 42,
  [81] = 81,
  [82] = 82,
  [83] = 47,
  [84] = 46,
  [85] = 85,
  [86] = 86,
  [87] = 43,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 85,
  [93] = 91,
  [94] = 68,
  [95] = 90,
  [96] = 67,
  [97] = 66,
  [98] = 88,
  [99] = 72,
  [100] = 82,
  [101] = 86,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 109,
  [111] = 105,
  [112] = 108,
  [113] = 106,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') ADVANCE(4);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '_') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(7);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(4);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '_') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(7);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(aux_sym_markup_leading_whitespace_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(aux_sym_newline_token1);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(aux_sym_whitespace_token1);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_special_token1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_special_token1);
      if (lookahead == '\n') ADVANCE(4);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 1, .external_lex_state = 3},
  [7] = {.lex_state = 1, .external_lex_state = 4},
  [8] = {.lex_state = 1, .external_lex_state = 5},
  [9] = {.lex_state = 1, .external_lex_state = 5},
  [10] = {.lex_state = 1, .external_lex_state = 4},
  [11] = {.lex_state = 1, .external_lex_state = 6},
  [12] = {.lex_state = 1, .external_lex_state = 7},
  [13] = {.lex_state = 1, .external_lex_state = 6},
  [14] = {.lex_state = 1, .external_lex_state = 7},
  [15] = {.lex_state = 1, .external_lex_state = 7},
  [16] = {.lex_state = 1, .external_lex_state = 6},
  [17] = {.lex_state = 1, .external_lex_state = 7},
  [18] = {.lex_state = 1, .external_lex_state = 8},
  [19] = {.lex_state = 1, .external_lex_state = 6},
  [20] = {.lex_state = 1, .external_lex_state = 8},
  [21] = {.lex_state = 1, .external_lex_state = 8},
  [22] = {.lex_state = 1, .external_lex_state = 8},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 0, .external_lex_state = 3},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 1, .external_lex_state = 9},
  [33] = {.lex_state = 1, .external_lex_state = 5},
  [34] = {.lex_state = 1, .external_lex_state = 4},
  [35] = {.lex_state = 1, .external_lex_state = 5},
  [36] = {.lex_state = 1, .external_lex_state = 4},
  [37] = {.lex_state = 1, .external_lex_state = 7},
  [38] = {.lex_state = 1, .external_lex_state = 5},
  [39] = {.lex_state = 1, .external_lex_state = 4},
  [40] = {.lex_state = 1, .external_lex_state = 6},
  [41] = {.lex_state = 1, .external_lex_state = 5},
  [42] = {.lex_state = 1, .external_lex_state = 6},
  [43] = {.lex_state = 1, .external_lex_state = 4},
  [44] = {.lex_state = 1, .external_lex_state = 5},
  [45] = {.lex_state = 1, .external_lex_state = 5},
  [46] = {.lex_state = 1, .external_lex_state = 5},
  [47] = {.lex_state = 1, .external_lex_state = 6},
  [48] = {.lex_state = 1, .external_lex_state = 6},
  [49] = {.lex_state = 1, .external_lex_state = 7},
  [50] = {.lex_state = 1, .external_lex_state = 4},
  [51] = {.lex_state = 1, .external_lex_state = 10},
  [52] = {.lex_state = 1, .external_lex_state = 4},
  [53] = {.lex_state = 1, .external_lex_state = 7},
  [54] = {.lex_state = 1, .external_lex_state = 5},
  [55] = {.lex_state = 1, .external_lex_state = 4},
  [56] = {.lex_state = 1, .external_lex_state = 7},
  [57] = {.lex_state = 1, .external_lex_state = 4},
  [58] = {.lex_state = 1, .external_lex_state = 7},
  [59] = {.lex_state = 1, .external_lex_state = 8},
  [60] = {.lex_state = 1, .external_lex_state = 11},
  [61] = {.lex_state = 1, .external_lex_state = 11},
  [62] = {.lex_state = 1, .external_lex_state = 11},
  [63] = {.lex_state = 1, .external_lex_state = 11},
  [64] = {.lex_state = 1, .external_lex_state = 12},
  [65] = {.lex_state = 1, .external_lex_state = 11},
  [66] = {.lex_state = 1, .external_lex_state = 7},
  [67] = {.lex_state = 1, .external_lex_state = 7},
  [68] = {.lex_state = 1, .external_lex_state = 7},
  [69] = {.lex_state = 1, .external_lex_state = 11},
  [70] = {.lex_state = 1, .external_lex_state = 6},
  [71] = {.lex_state = 1, .external_lex_state = 7},
  [72] = {.lex_state = 1, .external_lex_state = 7},
  [73] = {.lex_state = 1, .external_lex_state = 11},
  [74] = {.lex_state = 1, .external_lex_state = 6},
  [75] = {.lex_state = 1, .external_lex_state = 6},
  [76] = {.lex_state = 1, .external_lex_state = 6},
  [77] = {.lex_state = 1, .external_lex_state = 6},
  [78] = {.lex_state = 1, .external_lex_state = 6},
  [79] = {.lex_state = 1, .external_lex_state = 8},
  [80] = {.lex_state = 1, .external_lex_state = 8},
  [81] = {.lex_state = 1, .external_lex_state = 3},
  [82] = {.lex_state = 1, .external_lex_state = 7},
  [83] = {.lex_state = 1, .external_lex_state = 8},
  [84] = {.lex_state = 1, .external_lex_state = 11},
  [85] = {.lex_state = 1, .external_lex_state = 6},
  [86] = {.lex_state = 1, .external_lex_state = 7},
  [87] = {.lex_state = 1, .external_lex_state = 11},
  [88] = {.lex_state = 1, .external_lex_state = 6},
  [89] = {.lex_state = 1, .external_lex_state = 8},
  [90] = {.lex_state = 1, .external_lex_state = 7},
  [91] = {.lex_state = 1, .external_lex_state = 6},
  [92] = {.lex_state = 1, .external_lex_state = 8},
  [93] = {.lex_state = 1, .external_lex_state = 8},
  [94] = {.lex_state = 1, .external_lex_state = 8},
  [95] = {.lex_state = 1, .external_lex_state = 8},
  [96] = {.lex_state = 1, .external_lex_state = 8},
  [97] = {.lex_state = 1, .external_lex_state = 8},
  [98] = {.lex_state = 1, .external_lex_state = 8},
  [99] = {.lex_state = 1, .external_lex_state = 8},
  [100] = {.lex_state = 1, .external_lex_state = 8},
  [101] = {.lex_state = 1, .external_lex_state = 8},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0, .external_lex_state = 13},
  [106] = {.lex_state = 0, .external_lex_state = 13},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0, .external_lex_state = 14},
  [109] = {.lex_state = 0, .external_lex_state = 14},
  [110] = {.lex_state = 0, .external_lex_state = 14},
  [111] = {.lex_state = 0, .external_lex_state = 13},
  [112] = {.lex_state = 0, .external_lex_state = 14},
  [113] = {.lex_state = 0, .external_lex_state = 13},
};

enum {
  ts_external_token_last_token_non_word = 0,
  ts_external_token_last_token_word = 1,
  ts_external_token_strong_open = 2,
  ts_external_token_strong_close = 3,
  ts_external_token_italic_open = 4,
  ts_external_token_italic_close = 5,
  ts_external_token_heading_prefix = 6,
  ts_external_token_equalsigns = 7,
  ts_external_token___error_canary = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_last_token_non_word] = sym_last_token_non_word,
  [ts_external_token_last_token_word] = sym_last_token_word,
  [ts_external_token_strong_open] = sym_strong_open,
  [ts_external_token_strong_close] = sym_strong_close,
  [ts_external_token_italic_open] = sym_italic_open,
  [ts_external_token_italic_close] = sym_italic_close,
  [ts_external_token_heading_prefix] = sym_heading_prefix,
  [ts_external_token_equalsigns] = sym_equalsigns,
  [ts_external_token___error_canary] = sym___error_canary,
};

static const bool ts_external_scanner_states[15][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_last_token_non_word] = true,
    [ts_external_token_last_token_word] = true,
    [ts_external_token_strong_open] = true,
    [ts_external_token_strong_close] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_italic_close] = true,
    [ts_external_token_heading_prefix] = true,
    [ts_external_token_equalsigns] = true,
    [ts_external_token___error_canary] = true,
  },
  [2] = {
    [ts_external_token_last_token_non_word] = true,
    [ts_external_token_strong_open] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_heading_prefix] = true,
    [ts_external_token_equalsigns] = true,
  },
  [3] = {
    [ts_external_token_strong_open] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_heading_prefix] = true,
    [ts_external_token_equalsigns] = true,
  },
  [4] = {
    [ts_external_token_last_token_non_word] = true,
    [ts_external_token_strong_close] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_equalsigns] = true,
  },
  [5] = {
    [ts_external_token_last_token_non_word] = true,
    [ts_external_token_strong_open] = true,
    [ts_external_token_italic_close] = true,
    [ts_external_token_equalsigns] = true,
  },
  [6] = {
    [ts_external_token_strong_close] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_equalsigns] = true,
  },
  [7] = {
    [ts_external_token_strong_open] = true,
    [ts_external_token_italic_close] = true,
    [ts_external_token_equalsigns] = true,
  },
  [8] = {
    [ts_external_token_strong_open] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_equalsigns] = true,
  },
  [9] = {
    [ts_external_token_last_token_word] = true,
    [ts_external_token_strong_open] = true,
    [ts_external_token_italic_close] = true,
    [ts_external_token_equalsigns] = true,
  },
  [10] = {
    [ts_external_token_last_token_word] = true,
    [ts_external_token_strong_close] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_equalsigns] = true,
  },
  [11] = {
    [ts_external_token_last_token_non_word] = true,
    [ts_external_token_strong_open] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_equalsigns] = true,
  },
  [12] = {
    [ts_external_token_last_token_word] = true,
    [ts_external_token_strong_open] = true,
    [ts_external_token_italic_open] = true,
    [ts_external_token_equalsigns] = true,
  },
  [13] = {
    [ts_external_token_italic_close] = true,
  },
  [14] = {
    [ts_external_token_strong_close] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(1),
    [aux_sym_newline_token1] = ACTIONS(1),
    [aux_sym_whitespace_token1] = ACTIONS(1),
    [aux_sym_word_token1] = ACTIONS(1),
    [aux_sym_special_token1] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [sym_last_token_non_word] = ACTIONS(1),
    [sym_last_token_word] = ACTIONS(1),
    [sym_strong_open] = ACTIONS(1),
    [sym_strong_close] = ACTIONS(1),
    [sym_italic_open] = ACTIONS(1),
    [sym_italic_close] = ACTIONS(1),
    [sym_heading_prefix] = ACTIONS(1),
    [sym_equalsigns] = ACTIONS(1),
    [sym___error_canary] = ACTIONS(1),
  },
  [1] = {
    [sym_markup_block] = STATE(107),
    [sym__markup_content] = STATE(5),
    [sym_markup_leading_whitespace] = STATE(6),
    [sym_newline] = STATE(5),
    [sym_whitespace] = STATE(21),
    [sym_word] = STATE(21),
    [sym_special] = STATE(21),
    [sym_star] = STATE(21),
    [sym_strong] = STATE(21),
    [sym_italic] = STATE(21),
    [sym_heading] = STATE(5),
    [sym_line] = STATE(5),
    [sym_line_content] = STATE(104),
    [aux_sym_markup_block_repeat1] = STATE(5),
    [aux_sym_markup_leading_whitespace_repeat1] = STATE(23),
    [aux_sym_whitespace_repeat1] = STATE(59),
    [aux_sym_special_repeat1] = STATE(83),
    [aux_sym_heading_content_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(5),
    [aux_sym_newline_token1] = ACTIONS(7),
    [aux_sym_whitespace_token1] = ACTIONS(9),
    [aux_sym_word_token1] = ACTIONS(11),
    [aux_sym_special_token1] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [sym_last_token_non_word] = ACTIONS(17),
    [sym_strong_open] = ACTIONS(19),
    [sym_italic_open] = ACTIONS(21),
    [sym_heading_prefix] = ACTIONS(23),
    [sym_equalsigns] = ACTIONS(25),
  },
  [2] = {
    [sym__markup_content] = STATE(4),
    [sym_markup_leading_whitespace] = STATE(6),
    [sym_newline] = STATE(4),
    [sym_whitespace] = STATE(21),
    [sym_word] = STATE(21),
    [sym_special] = STATE(21),
    [sym_star] = STATE(21),
    [sym_strong] = STATE(21),
    [sym_italic] = STATE(21),
    [sym_heading] = STATE(4),
    [sym_line] = STATE(4),
    [sym_line_content] = STATE(104),
    [aux_sym_markup_block_repeat1] = STATE(4),
    [aux_sym_markup_leading_whitespace_repeat1] = STATE(23),
    [aux_sym_whitespace_repeat1] = STATE(59),
    [aux_sym_special_repeat1] = STATE(83),
    [aux_sym_heading_content_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(27),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(5),
    [aux_sym_newline_token1] = ACTIONS(7),
    [aux_sym_whitespace_token1] = ACTIONS(9),
    [aux_sym_word_token1] = ACTIONS(11),
    [aux_sym_special_token1] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [sym_strong_open] = ACTIONS(19),
    [sym_italic_open] = ACTIONS(21),
    [sym_heading_prefix] = ACTIONS(23),
    [sym_equalsigns] = ACTIONS(25),
  },
  [3] = {
    [sym__markup_content] = STATE(3),
    [sym_markup_leading_whitespace] = STATE(6),
    [sym_newline] = STATE(3),
    [sym_whitespace] = STATE(21),
    [sym_word] = STATE(21),
    [sym_special] = STATE(21),
    [sym_star] = STATE(21),
    [sym_strong] = STATE(21),
    [sym_italic] = STATE(21),
    [sym_heading] = STATE(3),
    [sym_line] = STATE(3),
    [sym_line_content] = STATE(104),
    [aux_sym_markup_block_repeat1] = STATE(3),
    [aux_sym_markup_leading_whitespace_repeat1] = STATE(23),
    [aux_sym_whitespace_repeat1] = STATE(59),
    [aux_sym_special_repeat1] = STATE(83),
    [aux_sym_heading_content_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(29),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(31),
    [aux_sym_newline_token1] = ACTIONS(34),
    [aux_sym_whitespace_token1] = ACTIONS(37),
    [aux_sym_word_token1] = ACTIONS(40),
    [aux_sym_special_token1] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(46),
    [sym_strong_open] = ACTIONS(49),
    [sym_italic_open] = ACTIONS(52),
    [sym_heading_prefix] = ACTIONS(55),
    [sym_equalsigns] = ACTIONS(58),
  },
  [4] = {
    [sym__markup_content] = STATE(3),
    [sym_markup_leading_whitespace] = STATE(6),
    [sym_newline] = STATE(3),
    [sym_whitespace] = STATE(21),
    [sym_word] = STATE(21),
    [sym_special] = STATE(21),
    [sym_star] = STATE(21),
    [sym_strong] = STATE(21),
    [sym_italic] = STATE(21),
    [sym_heading] = STATE(3),
    [sym_line] = STATE(3),
    [sym_line_content] = STATE(104),
    [aux_sym_markup_block_repeat1] = STATE(3),
    [aux_sym_markup_leading_whitespace_repeat1] = STATE(23),
    [aux_sym_whitespace_repeat1] = STATE(59),
    [aux_sym_special_repeat1] = STATE(83),
    [aux_sym_heading_content_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(61),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(5),
    [aux_sym_newline_token1] = ACTIONS(7),
    [aux_sym_whitespace_token1] = ACTIONS(9),
    [aux_sym_word_token1] = ACTIONS(11),
    [aux_sym_special_token1] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [sym_strong_open] = ACTIONS(19),
    [sym_italic_open] = ACTIONS(21),
    [sym_heading_prefix] = ACTIONS(23),
    [sym_equalsigns] = ACTIONS(25),
  },
  [5] = {
    [sym__markup_content] = STATE(3),
    [sym_markup_leading_whitespace] = STATE(6),
    [sym_newline] = STATE(3),
    [sym_whitespace] = STATE(21),
    [sym_word] = STATE(21),
    [sym_special] = STATE(21),
    [sym_star] = STATE(21),
    [sym_strong] = STATE(21),
    [sym_italic] = STATE(21),
    [sym_heading] = STATE(3),
    [sym_line] = STATE(3),
    [sym_line_content] = STATE(104),
    [aux_sym_markup_block_repeat1] = STATE(3),
    [aux_sym_markup_leading_whitespace_repeat1] = STATE(23),
    [aux_sym_whitespace_repeat1] = STATE(59),
    [aux_sym_special_repeat1] = STATE(83),
    [aux_sym_heading_content_repeat1] = STATE(21),
    [ts_builtin_sym_end] = ACTIONS(27),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(5),
    [aux_sym_newline_token1] = ACTIONS(7),
    [aux_sym_whitespace_token1] = ACTIONS(9),
    [aux_sym_word_token1] = ACTIONS(11),
    [aux_sym_special_token1] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [sym_strong_open] = ACTIONS(19),
    [sym_italic_open] = ACTIONS(21),
    [sym_heading_prefix] = ACTIONS(23),
    [sym_equalsigns] = ACTIONS(25),
  },
  [6] = {
    [sym_newline] = STATE(27),
    [sym_whitespace] = STATE(21),
    [sym_word] = STATE(21),
    [sym_special] = STATE(21),
    [sym_star] = STATE(21),
    [sym_strong] = STATE(21),
    [sym_italic] = STATE(21),
    [sym_heading] = STATE(27),
    [sym_line] = STATE(27),
    [sym_line_content] = STATE(104),
    [aux_sym_whitespace_repeat1] = STATE(59),
    [aux_sym_special_repeat1] = STATE(83),
    [aux_sym_heading_content_repeat1] = STATE(21),
    [aux_sym_newline_token1] = ACTIONS(7),
    [aux_sym_whitespace_token1] = ACTIONS(63),
    [aux_sym_word_token1] = ACTIONS(11),
    [aux_sym_special_token1] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [sym_strong_open] = ACTIONS(19),
    [sym_italic_open] = ACTIONS(21),
    [sym_heading_prefix] = ACTIONS(23),
    [sym_equalsigns] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(65), 1,
      aux_sym_newline_token1,
    ACTIONS(67), 1,
      aux_sym_whitespace_token1,
    ACTIONS(69), 1,
      aux_sym_word_token1,
    ACTIONS(71), 1,
      aux_sym_special_token1,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym__,
    ACTIONS(77), 1,
      sym_last_token_non_word,
    ACTIONS(79), 1,
      sym_strong_close,
    ACTIONS(81), 1,
      sym_italic_open,
    ACTIONS(83), 1,
      sym_equalsigns,
    STATE(47), 1,
      aux_sym_special_repeat1,
    STATE(48), 1,
      aux_sym_whitespace_repeat1,
    STATE(110), 1,
      sym_strong_content,
    STATE(19), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_italic,
      aux_sym_strong_content_repeat1,
  [50] = 14,
    ACTIONS(85), 1,
      aux_sym_newline_token1,
    ACTIONS(87), 1,
      aux_sym_whitespace_token1,
    ACTIONS(89), 1,
      aux_sym_word_token1,
    ACTIONS(91), 1,
      aux_sym_special_token1,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(97), 1,
      sym_last_token_non_word,
    ACTIONS(99), 1,
      sym_strong_open,
    ACTIONS(101), 1,
      sym_italic_close,
    ACTIONS(103), 1,
      sym_equalsigns,
    STATE(49), 1,
      aux_sym_whitespace_repeat1,
    STATE(53), 1,
      aux_sym_special_repeat1,
    STATE(105), 1,
      sym_italic_content,
    STATE(17), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_strong,
      aux_sym_italic_content_repeat1,
  [100] = 14,
    ACTIONS(85), 1,
      aux_sym_newline_token1,
    ACTIONS(87), 1,
      aux_sym_whitespace_token1,
    ACTIONS(89), 1,
      aux_sym_word_token1,
    ACTIONS(91), 1,
      aux_sym_special_token1,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(99), 1,
      sym_strong_open,
    ACTIONS(103), 1,
      sym_equalsigns,
    ACTIONS(105), 1,
      sym_last_token_non_word,
    ACTIONS(107), 1,
      sym_italic_close,
    STATE(49), 1,
      aux_sym_whitespace_repeat1,
    STATE(53), 1,
      aux_sym_special_repeat1,
    STATE(111), 1,
      sym_italic_content,
    STATE(17), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_strong,
      aux_sym_italic_content_repeat1,
  [150] = 14,
    ACTIONS(65), 1,
      aux_sym_newline_token1,
    ACTIONS(67), 1,
      aux_sym_whitespace_token1,
    ACTIONS(69), 1,
      aux_sym_word_token1,
    ACTIONS(71), 1,
      aux_sym_special_token1,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym__,
    ACTIONS(81), 1,
      sym_italic_open,
    ACTIONS(83), 1,
      sym_equalsigns,
    ACTIONS(109), 1,
      sym_last_token_non_word,
    ACTIONS(111), 1,
      sym_strong_close,
    STATE(47), 1,
      aux_sym_special_repeat1,
    STATE(48), 1,
      aux_sym_whitespace_repeat1,
    STATE(109), 1,
      sym_strong_content,
    STATE(19), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_italic,
      aux_sym_strong_content_repeat1,
  [200] = 13,
    ACTIONS(65), 1,
      aux_sym_newline_token1,
    ACTIONS(67), 1,
      aux_sym_whitespace_token1,
    ACTIONS(69), 1,
      aux_sym_word_token1,
    ACTIONS(71), 1,
      aux_sym_special_token1,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym__,
    ACTIONS(81), 1,
      sym_italic_open,
    ACTIONS(83), 1,
      sym_equalsigns,
    ACTIONS(113), 1,
      sym_strong_close,
    STATE(47), 1,
      aux_sym_special_repeat1,
    STATE(48), 1,
      aux_sym_whitespace_repeat1,
    STATE(112), 1,
      sym_strong_content,
    STATE(19), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_italic,
      aux_sym_strong_content_repeat1,
  [247] = 13,
    ACTIONS(85), 1,
      aux_sym_newline_token1,
    ACTIONS(87), 1,
      aux_sym_whitespace_token1,
    ACTIONS(89), 1,
      aux_sym_word_token1,
    ACTIONS(91), 1,
      aux_sym_special_token1,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(99), 1,
      sym_strong_open,
    ACTIONS(103), 1,
      sym_equalsigns,
    ACTIONS(115), 1,
      sym_italic_close,
    STATE(49), 1,
      aux_sym_whitespace_repeat1,
    STATE(53), 1,
      aux_sym_special_repeat1,
    STATE(113), 1,
      sym_italic_content,
    STATE(17), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_strong,
      aux_sym_italic_content_repeat1,
  [294] = 13,
    ACTIONS(65), 1,
      aux_sym_newline_token1,
    ACTIONS(67), 1,
      aux_sym_whitespace_token1,
    ACTIONS(69), 1,
      aux_sym_word_token1,
    ACTIONS(71), 1,
      aux_sym_special_token1,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym__,
    ACTIONS(81), 1,
      sym_italic_open,
    ACTIONS(83), 1,
      sym_equalsigns,
    ACTIONS(117), 1,
      sym_strong_close,
    STATE(47), 1,
      aux_sym_special_repeat1,
    STATE(48), 1,
      aux_sym_whitespace_repeat1,
    STATE(108), 1,
      sym_strong_content,
    STATE(19), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_italic,
      aux_sym_strong_content_repeat1,
  [341] = 13,
    ACTIONS(85), 1,
      aux_sym_newline_token1,
    ACTIONS(87), 1,
      aux_sym_whitespace_token1,
    ACTIONS(89), 1,
      aux_sym_word_token1,
    ACTIONS(91), 1,
      aux_sym_special_token1,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(99), 1,
      sym_strong_open,
    ACTIONS(103), 1,
      sym_equalsigns,
    ACTIONS(119), 1,
      sym_italic_close,
    STATE(49), 1,
      aux_sym_whitespace_repeat1,
    STATE(53), 1,
      aux_sym_special_repeat1,
    STATE(106), 1,
      sym_italic_content,
    STATE(17), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_strong,
      aux_sym_italic_content_repeat1,
  [388] = 12,
    ACTIONS(121), 1,
      aux_sym_newline_token1,
    ACTIONS(124), 1,
      aux_sym_whitespace_token1,
    ACTIONS(127), 1,
      aux_sym_word_token1,
    ACTIONS(130), 1,
      aux_sym_special_token1,
    ACTIONS(133), 1,
      anon_sym_STAR,
    ACTIONS(136), 1,
      anon_sym__,
    ACTIONS(139), 1,
      sym_strong_open,
    ACTIONS(142), 1,
      sym_italic_close,
    ACTIONS(144), 1,
      sym_equalsigns,
    STATE(49), 1,
      aux_sym_whitespace_repeat1,
    STATE(53), 1,
      aux_sym_special_repeat1,
    STATE(15), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_strong,
      aux_sym_italic_content_repeat1,
  [432] = 12,
    ACTIONS(147), 1,
      aux_sym_newline_token1,
    ACTIONS(150), 1,
      aux_sym_whitespace_token1,
    ACTIONS(153), 1,
      aux_sym_word_token1,
    ACTIONS(156), 1,
      aux_sym_special_token1,
    ACTIONS(159), 1,
      anon_sym_STAR,
    ACTIONS(162), 1,
      anon_sym__,
    ACTIONS(165), 1,
      sym_strong_close,
    ACTIONS(167), 1,
      sym_italic_open,
    ACTIONS(170), 1,
      sym_equalsigns,
    STATE(47), 1,
      aux_sym_special_repeat1,
    STATE(48), 1,
      aux_sym_whitespace_repeat1,
    STATE(16), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_italic,
      aux_sym_strong_content_repeat1,
  [476] = 12,
    ACTIONS(85), 1,
      aux_sym_newline_token1,
    ACTIONS(87), 1,
      aux_sym_whitespace_token1,
    ACTIONS(89), 1,
      aux_sym_word_token1,
    ACTIONS(91), 1,
      aux_sym_special_token1,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym__,
    ACTIONS(99), 1,
      sym_strong_open,
    ACTIONS(103), 1,
      sym_equalsigns,
    ACTIONS(173), 1,
      sym_italic_close,
    STATE(49), 1,
      aux_sym_whitespace_repeat1,
    STATE(53), 1,
      aux_sym_special_repeat1,
    STATE(15), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_strong,
      aux_sym_italic_content_repeat1,
  [520] = 13,
    ACTIONS(7), 1,
      aux_sym_newline_token1,
    ACTIONS(11), 1,
      aux_sym_word_token1,
    ACTIONS(13), 1,
      aux_sym_special_token1,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      sym_strong_open,
    ACTIONS(21), 1,
      sym_italic_open,
    ACTIONS(25), 1,
      sym_equalsigns,
    ACTIONS(63), 1,
      aux_sym_whitespace_token1,
    STATE(28), 1,
      sym_newline,
    STATE(59), 1,
      aux_sym_whitespace_repeat1,
    STATE(83), 1,
      aux_sym_special_repeat1,
    STATE(103), 1,
      sym_heading_content,
    STATE(22), 7,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_strong,
      sym_italic,
      aux_sym_heading_content_repeat1,
  [566] = 12,
    ACTIONS(65), 1,
      aux_sym_newline_token1,
    ACTIONS(67), 1,
      aux_sym_whitespace_token1,
    ACTIONS(69), 1,
      aux_sym_word_token1,
    ACTIONS(71), 1,
      aux_sym_special_token1,
    ACTIONS(73), 1,
      anon_sym_STAR,
    ACTIONS(75), 1,
      anon_sym__,
    ACTIONS(81), 1,
      sym_italic_open,
    ACTIONS(83), 1,
      sym_equalsigns,
    ACTIONS(175), 1,
      sym_strong_close,
    STATE(47), 1,
      aux_sym_special_repeat1,
    STATE(48), 1,
      aux_sym_whitespace_repeat1,
    STATE(16), 8,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_underscore,
      sym_italic,
      aux_sym_strong_content_repeat1,
  [610] = 11,
    ACTIONS(177), 1,
      aux_sym_newline_token1,
    ACTIONS(179), 1,
      aux_sym_whitespace_token1,
    ACTIONS(182), 1,
      aux_sym_word_token1,
    ACTIONS(185), 1,
      aux_sym_special_token1,
    ACTIONS(188), 1,
      anon_sym_STAR,
    ACTIONS(191), 1,
      sym_strong_open,
    ACTIONS(194), 1,
      sym_italic_open,
    ACTIONS(197), 1,
      sym_equalsigns,
    STATE(59), 1,
      aux_sym_whitespace_repeat1,
    STATE(83), 1,
      aux_sym_special_repeat1,
    STATE(20), 7,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_strong,
      sym_italic,
      aux_sym_heading_content_repeat1,
  [650] = 11,
    ACTIONS(11), 1,
      aux_sym_word_token1,
    ACTIONS(13), 1,
      aux_sym_special_token1,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      sym_strong_open,
    ACTIONS(21), 1,
      sym_italic_open,
    ACTIONS(25), 1,
      sym_equalsigns,
    ACTIONS(63), 1,
      aux_sym_whitespace_token1,
    ACTIONS(200), 1,
      aux_sym_newline_token1,
    STATE(59), 1,
      aux_sym_whitespace_repeat1,
    STATE(83), 1,
      aux_sym_special_repeat1,
    STATE(20), 7,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_strong,
      sym_italic,
      aux_sym_heading_content_repeat1,
  [690] = 11,
    ACTIONS(11), 1,
      aux_sym_word_token1,
    ACTIONS(13), 1,
      aux_sym_special_token1,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      sym_strong_open,
    ACTIONS(21), 1,
      sym_italic_open,
    ACTIONS(25), 1,
      sym_equalsigns,
    ACTIONS(63), 1,
      aux_sym_whitespace_token1,
    ACTIONS(202), 1,
      aux_sym_newline_token1,
    STATE(59), 1,
      aux_sym_whitespace_repeat1,
    STATE(83), 1,
      aux_sym_special_repeat1,
    STATE(20), 7,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_strong,
      sym_italic,
      aux_sym_heading_content_repeat1,
  [730] = 5,
    ACTIONS(204), 1,
      aux_sym_markup_leading_whitespace_token1,
    ACTIONS(210), 1,
      sym_last_token_non_word,
    STATE(24), 1,
      aux_sym_markup_leading_whitespace_repeat1,
    ACTIONS(208), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(206), 7,
      sym_strong_open,
      sym_italic_open,
      sym_heading_prefix,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [753] = 4,
    ACTIONS(212), 1,
      aux_sym_markup_leading_whitespace_token1,
    STATE(24), 1,
      aux_sym_markup_leading_whitespace_repeat1,
    ACTIONS(217), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(215), 8,
      sym_last_token_non_word,
      sym_strong_open,
      sym_italic_open,
      sym_heading_prefix,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [774] = 3,
    ACTIONS(223), 1,
      sym_last_token_non_word,
    ACTIONS(221), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(219), 9,
      sym_strong_open,
      sym_italic_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [793] = 2,
    ACTIONS(227), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(225), 9,
      sym_strong_open,
      sym_italic_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [809] = 2,
    ACTIONS(231), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(229), 9,
      sym_strong_open,
      sym_italic_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [825] = 2,
    ACTIONS(235), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(233), 9,
      sym_strong_open,
      sym_italic_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [841] = 2,
    ACTIONS(239), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(237), 9,
      sym_strong_open,
      sym_italic_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [857] = 2,
    ACTIONS(243), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(241), 9,
      sym_strong_open,
      sym_italic_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [873] = 2,
    ACTIONS(247), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(245), 9,
      sym_strong_open,
      sym_italic_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [889] = 3,
    ACTIONS(251), 1,
      aux_sym_special_token1,
    ACTIONS(253), 1,
      sym_last_token_word,
    ACTIONS(249), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [906] = 3,
    ACTIONS(257), 1,
      aux_sym_special_token1,
    ACTIONS(259), 1,
      sym_last_token_non_word,
    ACTIONS(255), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [923] = 3,
    ACTIONS(263), 1,
      aux_sym_special_token1,
    ACTIONS(265), 1,
      sym_last_token_non_word,
    ACTIONS(261), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [940] = 3,
    ACTIONS(269), 1,
      aux_sym_special_token1,
    ACTIONS(271), 1,
      sym_last_token_non_word,
    ACTIONS(267), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [957] = 3,
    ACTIONS(275), 1,
      aux_sym_special_token1,
    ACTIONS(277), 1,
      sym_last_token_non_word,
    ACTIONS(273), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [974] = 4,
    ACTIONS(281), 1,
      aux_sym_special_token1,
    ACTIONS(284), 1,
      sym_equalsigns,
    STATE(37), 1,
      aux_sym_special_repeat1,
    ACTIONS(279), 7,
      sym_strong_open,
      sym_italic_close,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [993] = 3,
    ACTIONS(289), 1,
      aux_sym_special_token1,
    ACTIONS(291), 1,
      sym_last_token_non_word,
    ACTIONS(287), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1010] = 3,
    ACTIONS(257), 1,
      aux_sym_special_token1,
    ACTIONS(293), 1,
      sym_last_token_non_word,
    ACTIONS(255), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1027] = 4,
    ACTIONS(295), 1,
      aux_sym_special_token1,
    ACTIONS(298), 1,
      sym_equalsigns,
    STATE(40), 1,
      aux_sym_special_repeat1,
    ACTIONS(279), 7,
      sym_strong_close,
      sym_italic_open,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1046] = 3,
    ACTIONS(303), 1,
      aux_sym_special_token1,
    ACTIONS(305), 1,
      sym_last_token_non_word,
    ACTIONS(301), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1063] = 4,
    ACTIONS(309), 1,
      aux_sym_whitespace_token1,
    ACTIONS(312), 1,
      aux_sym_special_token1,
    STATE(42), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(307), 7,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1082] = 3,
    ACTIONS(316), 1,
      aux_sym_special_token1,
    ACTIONS(318), 1,
      sym_last_token_non_word,
    ACTIONS(314), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1099] = 3,
    ACTIONS(322), 1,
      aux_sym_special_token1,
    ACTIONS(324), 1,
      sym_last_token_non_word,
    ACTIONS(320), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1116] = 3,
    ACTIONS(328), 1,
      aux_sym_special_token1,
    ACTIONS(330), 1,
      sym_last_token_non_word,
    ACTIONS(326), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1133] = 3,
    ACTIONS(334), 1,
      aux_sym_special_token1,
    ACTIONS(336), 1,
      sym_last_token_non_word,
    ACTIONS(332), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1150] = 4,
    ACTIONS(71), 1,
      aux_sym_special_token1,
    ACTIONS(83), 1,
      sym_equalsigns,
    STATE(40), 1,
      aux_sym_special_repeat1,
    ACTIONS(338), 7,
      sym_strong_close,
      sym_italic_open,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1169] = 4,
    ACTIONS(67), 1,
      aux_sym_whitespace_token1,
    ACTIONS(342), 1,
      aux_sym_special_token1,
    STATE(42), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(340), 7,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1188] = 4,
    ACTIONS(87), 1,
      aux_sym_whitespace_token1,
    ACTIONS(342), 1,
      aux_sym_special_token1,
    STATE(56), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(340), 7,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1207] = 3,
    ACTIONS(322), 1,
      aux_sym_special_token1,
    ACTIONS(344), 1,
      sym_last_token_non_word,
    ACTIONS(320), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1224] = 3,
    ACTIONS(251), 1,
      aux_sym_special_token1,
    ACTIONS(346), 1,
      sym_last_token_word,
    ACTIONS(249), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1241] = 3,
    ACTIONS(303), 1,
      aux_sym_special_token1,
    ACTIONS(348), 1,
      sym_last_token_non_word,
    ACTIONS(301), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1258] = 4,
    ACTIONS(91), 1,
      aux_sym_special_token1,
    ACTIONS(103), 1,
      sym_equalsigns,
    STATE(37), 1,
      aux_sym_special_repeat1,
    ACTIONS(338), 7,
      sym_strong_open,
      sym_italic_close,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1277] = 3,
    ACTIONS(221), 1,
      aux_sym_special_token1,
    ACTIONS(350), 1,
      sym_last_token_non_word,
    ACTIONS(219), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1294] = 3,
    ACTIONS(221), 1,
      aux_sym_special_token1,
    ACTIONS(352), 1,
      sym_last_token_non_word,
    ACTIONS(219), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1311] = 4,
    ACTIONS(312), 1,
      aux_sym_special_token1,
    ACTIONS(354), 1,
      aux_sym_whitespace_token1,
    STATE(56), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(307), 7,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1330] = 3,
    ACTIONS(328), 1,
      aux_sym_special_token1,
    ACTIONS(357), 1,
      sym_last_token_non_word,
    ACTIONS(326), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1347] = 2,
    ACTIONS(361), 1,
      aux_sym_special_token1,
    ACTIONS(359), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1361] = 4,
    ACTIONS(63), 1,
      aux_sym_whitespace_token1,
    ACTIONS(342), 1,
      aux_sym_special_token1,
    STATE(80), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(340), 6,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1379] = 3,
    ACTIONS(263), 1,
      aux_sym_special_token1,
    ACTIONS(363), 1,
      sym_last_token_non_word,
    ACTIONS(261), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1395] = 3,
    ACTIONS(269), 1,
      aux_sym_special_token1,
    ACTIONS(365), 1,
      sym_last_token_non_word,
    ACTIONS(267), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1411] = 3,
    ACTIONS(328), 1,
      aux_sym_special_token1,
    ACTIONS(367), 1,
      sym_last_token_non_word,
    ACTIONS(326), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1427] = 3,
    ACTIONS(303), 1,
      aux_sym_special_token1,
    ACTIONS(369), 1,
      sym_last_token_non_word,
    ACTIONS(301), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1443] = 3,
    ACTIONS(251), 1,
      aux_sym_special_token1,
    ACTIONS(371), 1,
      sym_last_token_word,
    ACTIONS(249), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1459] = 3,
    ACTIONS(322), 1,
      aux_sym_special_token1,
    ACTIONS(373), 1,
      sym_last_token_non_word,
    ACTIONS(320), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1475] = 2,
    ACTIONS(377), 1,
      aux_sym_special_token1,
    ACTIONS(375), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1489] = 2,
    ACTIONS(381), 1,
      aux_sym_special_token1,
    ACTIONS(379), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1503] = 2,
    ACTIONS(312), 1,
      aux_sym_special_token1,
    ACTIONS(307), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1517] = 3,
    ACTIONS(275), 1,
      aux_sym_special_token1,
    ACTIONS(383), 1,
      sym_last_token_non_word,
    ACTIONS(273), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1533] = 2,
    ACTIONS(361), 1,
      aux_sym_special_token1,
    ACTIONS(359), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1547] = 2,
    ACTIONS(239), 1,
      aux_sym_special_token1,
    ACTIONS(237), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1561] = 2,
    ACTIONS(385), 1,
      aux_sym_special_token1,
    ACTIONS(279), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1575] = 3,
    ACTIONS(289), 1,
      aux_sym_special_token1,
    ACTIONS(387), 1,
      sym_last_token_non_word,
    ACTIONS(287), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1591] = 2,
    ACTIONS(385), 1,
      aux_sym_special_token1,
    ACTIONS(279), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1605] = 2,
    ACTIONS(239), 1,
      aux_sym_special_token1,
    ACTIONS(237), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1619] = 2,
    ACTIONS(312), 1,
      aux_sym_special_token1,
    ACTIONS(307), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1633] = 2,
    ACTIONS(381), 1,
      aux_sym_special_token1,
    ACTIONS(379), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1647] = 2,
    ACTIONS(377), 1,
      aux_sym_special_token1,
    ACTIONS(375), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1661] = 4,
    ACTIONS(389), 1,
      aux_sym_special_token1,
    ACTIONS(392), 1,
      sym_equalsigns,
    STATE(79), 1,
      aux_sym_special_repeat1,
    ACTIONS(279), 6,
      sym_strong_open,
      sym_italic_open,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1679] = 4,
    ACTIONS(312), 1,
      aux_sym_special_token1,
    ACTIONS(395), 1,
      aux_sym_whitespace_token1,
    STATE(80), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(307), 6,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1697] = 2,
    ACTIONS(400), 1,
      aux_sym_special_token1,
    ACTIONS(398), 8,
      sym_strong_open,
      sym_italic_open,
      sym_heading_prefix,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1711] = 2,
    ACTIONS(289), 1,
      aux_sym_special_token1,
    ACTIONS(287), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1725] = 4,
    ACTIONS(13), 1,
      aux_sym_special_token1,
    ACTIONS(25), 1,
      sym_equalsigns,
    STATE(79), 1,
      aux_sym_special_repeat1,
    ACTIONS(338), 6,
      sym_strong_open,
      sym_italic_open,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1743] = 3,
    ACTIONS(334), 1,
      aux_sym_special_token1,
    ACTIONS(402), 1,
      sym_last_token_non_word,
    ACTIONS(332), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1759] = 2,
    ACTIONS(275), 1,
      aux_sym_special_token1,
    ACTIONS(273), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1773] = 2,
    ACTIONS(269), 1,
      aux_sym_special_token1,
    ACTIONS(267), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1787] = 3,
    ACTIONS(316), 1,
      aux_sym_special_token1,
    ACTIONS(404), 1,
      sym_last_token_non_word,
    ACTIONS(314), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1803] = 2,
    ACTIONS(263), 1,
      aux_sym_special_token1,
    ACTIONS(261), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1817] = 3,
    ACTIONS(408), 1,
      aux_sym_special_token1,
    STATE(80), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(406), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1833] = 2,
    ACTIONS(412), 1,
      aux_sym_special_token1,
    ACTIONS(410), 8,
      sym_strong_open,
      sym_italic_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1847] = 2,
    ACTIONS(416), 1,
      aux_sym_special_token1,
    ACTIONS(414), 8,
      sym_strong_close,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
      anon_sym__,
  [1861] = 2,
    ACTIONS(275), 1,
      aux_sym_special_token1,
    ACTIONS(273), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1874] = 2,
    ACTIONS(416), 1,
      aux_sym_special_token1,
    ACTIONS(414), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1887] = 2,
    ACTIONS(312), 1,
      aux_sym_special_token1,
    ACTIONS(307), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1900] = 2,
    ACTIONS(412), 1,
      aux_sym_special_token1,
    ACTIONS(410), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1913] = 2,
    ACTIONS(381), 1,
      aux_sym_special_token1,
    ACTIONS(379), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1926] = 2,
    ACTIONS(377), 1,
      aux_sym_special_token1,
    ACTIONS(375), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1939] = 2,
    ACTIONS(263), 1,
      aux_sym_special_token1,
    ACTIONS(261), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1952] = 2,
    ACTIONS(385), 1,
      aux_sym_special_token1,
    ACTIONS(279), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1965] = 2,
    ACTIONS(289), 1,
      aux_sym_special_token1,
    ACTIONS(287), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1978] = 2,
    ACTIONS(269), 1,
      aux_sym_special_token1,
    ACTIONS(267), 7,
      sym_strong_open,
      sym_italic_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [1991] = 5,
    ACTIONS(7), 1,
      aux_sym_newline_token1,
    ACTIONS(63), 1,
      aux_sym_whitespace_token1,
    STATE(18), 1,
      sym_heading_whitespace,
    STATE(26), 1,
      sym_newline,
    STATE(89), 1,
      aux_sym_whitespace_repeat1,
  [2007] = 2,
    ACTIONS(7), 1,
      aux_sym_newline_token1,
    STATE(30), 1,
      sym_newline,
  [2014] = 2,
    ACTIONS(7), 1,
      aux_sym_newline_token1,
    STATE(31), 1,
      sym_newline,
  [2021] = 1,
    ACTIONS(119), 1,
      sym_italic_close,
  [2025] = 1,
    ACTIONS(418), 1,
      sym_italic_close,
  [2029] = 1,
    ACTIONS(420), 1,
      ts_builtin_sym_end,
  [2033] = 1,
    ACTIONS(422), 1,
      sym_strong_close,
  [2037] = 1,
    ACTIONS(113), 1,
      sym_strong_close,
  [2041] = 1,
    ACTIONS(117), 1,
      sym_strong_close,
  [2045] = 1,
    ACTIONS(115), 1,
      sym_italic_close,
  [2049] = 1,
    ACTIONS(424), 1,
      sym_strong_close,
  [2053] = 1,
    ACTIONS(426), 1,
      sym_italic_close,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 50,
  [SMALL_STATE(9)] = 100,
  [SMALL_STATE(10)] = 150,
  [SMALL_STATE(11)] = 200,
  [SMALL_STATE(12)] = 247,
  [SMALL_STATE(13)] = 294,
  [SMALL_STATE(14)] = 341,
  [SMALL_STATE(15)] = 388,
  [SMALL_STATE(16)] = 432,
  [SMALL_STATE(17)] = 476,
  [SMALL_STATE(18)] = 520,
  [SMALL_STATE(19)] = 566,
  [SMALL_STATE(20)] = 610,
  [SMALL_STATE(21)] = 650,
  [SMALL_STATE(22)] = 690,
  [SMALL_STATE(23)] = 730,
  [SMALL_STATE(24)] = 753,
  [SMALL_STATE(25)] = 774,
  [SMALL_STATE(26)] = 793,
  [SMALL_STATE(27)] = 809,
  [SMALL_STATE(28)] = 825,
  [SMALL_STATE(29)] = 841,
  [SMALL_STATE(30)] = 857,
  [SMALL_STATE(31)] = 873,
  [SMALL_STATE(32)] = 889,
  [SMALL_STATE(33)] = 906,
  [SMALL_STATE(34)] = 923,
  [SMALL_STATE(35)] = 940,
  [SMALL_STATE(36)] = 957,
  [SMALL_STATE(37)] = 974,
  [SMALL_STATE(38)] = 993,
  [SMALL_STATE(39)] = 1010,
  [SMALL_STATE(40)] = 1027,
  [SMALL_STATE(41)] = 1046,
  [SMALL_STATE(42)] = 1063,
  [SMALL_STATE(43)] = 1082,
  [SMALL_STATE(44)] = 1099,
  [SMALL_STATE(45)] = 1116,
  [SMALL_STATE(46)] = 1133,
  [SMALL_STATE(47)] = 1150,
  [SMALL_STATE(48)] = 1169,
  [SMALL_STATE(49)] = 1188,
  [SMALL_STATE(50)] = 1207,
  [SMALL_STATE(51)] = 1224,
  [SMALL_STATE(52)] = 1241,
  [SMALL_STATE(53)] = 1258,
  [SMALL_STATE(54)] = 1277,
  [SMALL_STATE(55)] = 1294,
  [SMALL_STATE(56)] = 1311,
  [SMALL_STATE(57)] = 1330,
  [SMALL_STATE(58)] = 1347,
  [SMALL_STATE(59)] = 1361,
  [SMALL_STATE(60)] = 1379,
  [SMALL_STATE(61)] = 1395,
  [SMALL_STATE(62)] = 1411,
  [SMALL_STATE(63)] = 1427,
  [SMALL_STATE(64)] = 1443,
  [SMALL_STATE(65)] = 1459,
  [SMALL_STATE(66)] = 1475,
  [SMALL_STATE(67)] = 1489,
  [SMALL_STATE(68)] = 1503,
  [SMALL_STATE(69)] = 1517,
  [SMALL_STATE(70)] = 1533,
  [SMALL_STATE(71)] = 1547,
  [SMALL_STATE(72)] = 1561,
  [SMALL_STATE(73)] = 1575,
  [SMALL_STATE(74)] = 1591,
  [SMALL_STATE(75)] = 1605,
  [SMALL_STATE(76)] = 1619,
  [SMALL_STATE(77)] = 1633,
  [SMALL_STATE(78)] = 1647,
  [SMALL_STATE(79)] = 1661,
  [SMALL_STATE(80)] = 1679,
  [SMALL_STATE(81)] = 1697,
  [SMALL_STATE(82)] = 1711,
  [SMALL_STATE(83)] = 1725,
  [SMALL_STATE(84)] = 1743,
  [SMALL_STATE(85)] = 1759,
  [SMALL_STATE(86)] = 1773,
  [SMALL_STATE(87)] = 1787,
  [SMALL_STATE(88)] = 1803,
  [SMALL_STATE(89)] = 1817,
  [SMALL_STATE(90)] = 1833,
  [SMALL_STATE(91)] = 1847,
  [SMALL_STATE(92)] = 1861,
  [SMALL_STATE(93)] = 1874,
  [SMALL_STATE(94)] = 1887,
  [SMALL_STATE(95)] = 1900,
  [SMALL_STATE(96)] = 1913,
  [SMALL_STATE(97)] = 1926,
  [SMALL_STATE(98)] = 1939,
  [SMALL_STATE(99)] = 1952,
  [SMALL_STATE(100)] = 1965,
  [SMALL_STATE(101)] = 1978,
  [SMALL_STATE(102)] = 1991,
  [SMALL_STATE(103)] = 2007,
  [SMALL_STATE(104)] = 2014,
  [SMALL_STATE(105)] = 2021,
  [SMALL_STATE(106)] = 2025,
  [SMALL_STATE(107)] = 2029,
  [SMALL_STATE(108)] = 2033,
  [SMALL_STATE(109)] = 2037,
  [SMALL_STATE(110)] = 2041,
  [SMALL_STATE(111)] = 2045,
  [SMALL_STATE(112)] = 2049,
  [SMALL_STATE(113)] = 2053,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_block, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_block, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(23),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(25),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(63),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(64),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(62),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(65),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(7),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(8),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(102),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(62),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_block, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_content_repeat1, 2), SHIFT_REPEAT(54),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_content_repeat1, 2), SHIFT_REPEAT(41),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_content_repeat1, 2), SHIFT_REPEAT(32),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_italic_content_repeat1, 2), SHIFT_REPEAT(45),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_content_repeat1, 2), SHIFT_REPEAT(44),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_content_repeat1, 2), SHIFT_REPEAT(33),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_content_repeat1, 2), SHIFT_REPEAT(10),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_italic_content_repeat1, 2),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_italic_content_repeat1, 2), SHIFT_REPEAT(45),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(55),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(52),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(51),
  [156] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(57),
  [159] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(50),
  [162] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(39),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(9),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(57),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic_content, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong_content, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(63),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(64),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(62),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(65),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(7),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(8),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(62),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_content, 1),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_content, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_leading_whitespace, 1),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_leading_whitespace, 1),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_leading_whitespace_repeat1, 2), SHIFT_REPEAT(24),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_markup_leading_whitespace_repeat1, 2),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_markup_leading_whitespace_repeat1, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_newline, 1),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_newline, 1),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 2),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 2),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__markup_content, 2),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__markup_content, 2),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 3),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_newline, 2),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_newline, 2),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 4),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 4),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 2),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 1),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_underscore, 1),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_underscore, 1),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 4),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 4),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong, 4),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong, 4),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 3),
  [275] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 3),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_special_repeat1, 2),
  [281] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_special_repeat1, 2), SHIFT_REPEAT(45),
  [284] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_special_repeat1, 2), SHIFT_REPEAT(45),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong, 3),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong, 3),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [295] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_special_repeat1, 2), SHIFT_REPEAT(57),
  [298] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_special_repeat1, 2), SHIFT_REPEAT(57),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_whitespace_repeat1, 1),
  [303] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_whitespace_repeat1, 1),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_whitespace_repeat1, 2),
  [309] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_whitespace_repeat1, 2), SHIFT_REPEAT(52),
  [312] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_whitespace_repeat1, 2),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 2),
  [316] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 2),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_star, 1),
  [322] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_star, 1),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_special_repeat1, 1),
  [328] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_special_repeat1, 1),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong, 2),
  [334] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong, 2),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special, 1),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_whitespace, 1),
  [342] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_whitespace, 1),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [354] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_whitespace_repeat1, 2), SHIFT_REPEAT(41),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_underscore, 2),
  [361] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_underscore, 2),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [375] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_star, 2),
  [377] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_star, 2),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 2),
  [381] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 2),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [385] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_special_repeat1, 2),
  [387] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [389] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_special_repeat1, 2), SHIFT_REPEAT(62),
  [392] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_special_repeat1, 2), SHIFT_REPEAT(62),
  [395] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_whitespace_repeat1, 2), SHIFT_REPEAT(63),
  [398] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_leading_whitespace, 2),
  [400] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_leading_whitespace, 2),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [406] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_whitespace, 1),
  [408] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading_whitespace, 1),
  [410] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong, 5),
  [412] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong, 5),
  [414] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_italic, 5),
  [416] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_italic, 5),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [420] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [426] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_typst_external_scanner_create(void);
void tree_sitter_typst_external_scanner_destroy(void *);
bool tree_sitter_typst_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_typst_external_scanner_serialize(void *, char *);
void tree_sitter_typst_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_typst(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_typst_external_scanner_create,
      tree_sitter_typst_external_scanner_destroy,
      tree_sitter_typst_external_scanner_scan,
      tree_sitter_typst_external_scanner_serialize,
      tree_sitter_typst_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
