#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 7
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  aux_sym_markup_leading_whitespace_token1 = 1,
  aux_sym_newline_token1 = 2,
  aux_sym_whitespace_token1 = 3,
  aux_sym_word_token1 = 4,
  aux_sym_special_token1 = 5,
  anon_sym_STAR = 6,
  sym_last_token_non_word = 7,
  sym_last_token_word = 8,
  sym_strong_open = 9,
  sym_strong_close = 10,
  sym_heading_prefix = 11,
  sym_equalsigns = 12,
  sym___error_canary = 13,
  sym_markup_block = 14,
  sym__markup_content = 15,
  sym_markup_leading_whitespace = 16,
  sym_newline = 17,
  sym_whitespace = 18,
  sym_word = 19,
  sym_special = 20,
  sym_star = 21,
  sym_strong = 22,
  sym_strong_content = 23,
  sym_heading = 24,
  sym_heading_whitespace = 25,
  sym_heading_content = 26,
  sym_line = 27,
  sym_line_content = 28,
  aux_sym_markup_block_repeat1 = 29,
  aux_sym_markup_leading_whitespace_repeat1 = 30,
  aux_sym_whitespace_repeat1 = 31,
  aux_sym_special_repeat1 = 32,
  aux_sym_strong_content_repeat1 = 33,
  aux_sym_heading_content_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_markup_leading_whitespace_token1] = "markup_leading_whitespace_token1",
  [aux_sym_newline_token1] = "newline_token1",
  [aux_sym_whitespace_token1] = "whitespace_token1",
  [aux_sym_word_token1] = "word_token1",
  [aux_sym_special_token1] = "special_token1",
  [anon_sym_STAR] = "*",
  [sym_last_token_non_word] = "last_token_non_word",
  [sym_last_token_word] = "last_token_word",
  [sym_strong_open] = "strong_open",
  [sym_strong_close] = "strong_close",
  [sym_heading_prefix] = "heading_prefix",
  [sym_equalsigns] = "equalsigns",
  [sym___error_canary] = "__error_canary",
  [sym_markup_block] = "markup_block",
  [sym__markup_content] = "_markup_content",
  [sym_markup_leading_whitespace] = "markup_leading_whitespace",
  [sym_newline] = "newline",
  [sym_whitespace] = "whitespace",
  [sym_word] = "word",
  [sym_special] = "special",
  [sym_star] = "star",
  [sym_strong] = "strong",
  [sym_strong_content] = "strong_content",
  [sym_heading] = "heading",
  [sym_heading_whitespace] = "heading_whitespace",
  [sym_heading_content] = "heading_content",
  [sym_line] = "line",
  [sym_line_content] = "line_content",
  [aux_sym_markup_block_repeat1] = "markup_block_repeat1",
  [aux_sym_markup_leading_whitespace_repeat1] = "markup_leading_whitespace_repeat1",
  [aux_sym_whitespace_repeat1] = "whitespace_repeat1",
  [aux_sym_special_repeat1] = "special_repeat1",
  [aux_sym_strong_content_repeat1] = "strong_content_repeat1",
  [aux_sym_heading_content_repeat1] = "heading_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_markup_leading_whitespace_token1] = aux_sym_markup_leading_whitespace_token1,
  [aux_sym_newline_token1] = aux_sym_newline_token1,
  [aux_sym_whitespace_token1] = aux_sym_whitespace_token1,
  [aux_sym_word_token1] = aux_sym_word_token1,
  [aux_sym_special_token1] = aux_sym_special_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [sym_last_token_non_word] = sym_last_token_non_word,
  [sym_last_token_word] = sym_last_token_word,
  [sym_strong_open] = sym_strong_open,
  [sym_strong_close] = sym_strong_close,
  [sym_heading_prefix] = sym_heading_prefix,
  [sym_equalsigns] = sym_equalsigns,
  [sym___error_canary] = sym___error_canary,
  [sym_markup_block] = sym_markup_block,
  [sym__markup_content] = sym__markup_content,
  [sym_markup_leading_whitespace] = sym_markup_leading_whitespace,
  [sym_newline] = sym_newline,
  [sym_whitespace] = sym_whitespace,
  [sym_word] = sym_word,
  [sym_special] = sym_special,
  [sym_star] = sym_star,
  [sym_strong] = sym_strong,
  [sym_strong_content] = sym_strong_content,
  [sym_heading] = sym_heading,
  [sym_heading_whitespace] = sym_heading_whitespace,
  [sym_heading_content] = sym_heading_content,
  [sym_line] = sym_line,
  [sym_line_content] = sym_line_content,
  [aux_sym_markup_block_repeat1] = aux_sym_markup_block_repeat1,
  [aux_sym_markup_leading_whitespace_repeat1] = aux_sym_markup_leading_whitespace_repeat1,
  [aux_sym_whitespace_repeat1] = aux_sym_whitespace_repeat1,
  [aux_sym_special_repeat1] = aux_sym_special_repeat1,
  [aux_sym_strong_content_repeat1] = aux_sym_strong_content_repeat1,
  [aux_sym_heading_content_repeat1] = aux_sym_heading_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_markup_leading_whitespace_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_newline_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_whitespace_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_word_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_special_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [sym_last_token_non_word] = {
    .visible = true,
    .named = true,
  },
  [sym_last_token_word] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_open] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_close] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_equalsigns] = {
    .visible = true,
    .named = true,
  },
  [sym___error_canary] = {
    .visible = false,
    .named = true,
  },
  [sym_markup_block] = {
    .visible = true,
    .named = true,
  },
  [sym__markup_content] = {
    .visible = false,
    .named = true,
  },
  [sym_markup_leading_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_special] = {
    .visible = true,
    .named = true,
  },
  [sym_star] = {
    .visible = true,
    .named = true,
  },
  [sym_strong] = {
    .visible = true,
    .named = true,
  },
  [sym_strong_content] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_whitespace] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_content] = {
    .visible = true,
    .named = true,
  },
  [sym_line] = {
    .visible = true,
    .named = true,
  },
  [sym_line_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_markup_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markup_leading_whitespace_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_whitespace_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_special_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_strong_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 24,
  [30] = 30,
  [31] = 25,
  [32] = 32,
  [33] = 28,
  [34] = 34,
  [35] = 35,
  [36] = 27,
  [37] = 26,
  [38] = 17,
  [39] = 39,
  [40] = 40,
  [41] = 40,
  [42] = 30,
  [43] = 43,
  [44] = 44,
  [45] = 35,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 22,
  [54] = 51,
  [55] = 50,
  [56] = 49,
  [57] = 52,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '\n') ADVANCE(4);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(7);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(4);
      if (lookahead == '\r') ADVANCE(8);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(7);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(aux_sym_markup_leading_whitespace_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(aux_sym_newline_token1);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(aux_sym_whitespace_token1);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_word_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_special_token1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_special_token1);
      if (lookahead == '\n') ADVANCE(4);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 1, .external_lex_state = 3},
  [7] = {.lex_state = 1, .external_lex_state = 4},
  [8] = {.lex_state = 1, .external_lex_state = 5},
  [9] = {.lex_state = 1, .external_lex_state = 6},
  [10] = {.lex_state = 1, .external_lex_state = 6},
  [11] = {.lex_state = 1, .external_lex_state = 4},
  [12] = {.lex_state = 1, .external_lex_state = 4},
  [13] = {.lex_state = 1, .external_lex_state = 4},
  [14] = {.lex_state = 1, .external_lex_state = 6},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 3},
  [19] = {.lex_state = 0, .external_lex_state = 3},
  [20] = {.lex_state = 0, .external_lex_state = 3},
  [21] = {.lex_state = 0, .external_lex_state = 3},
  [22] = {.lex_state = 0, .external_lex_state = 3},
  [23] = {.lex_state = 0, .external_lex_state = 3},
  [24] = {.lex_state = 1, .external_lex_state = 4},
  [25] = {.lex_state = 1, .external_lex_state = 7},
  [26] = {.lex_state = 1, .external_lex_state = 6},
  [27] = {.lex_state = 1, .external_lex_state = 6},
  [28] = {.lex_state = 1, .external_lex_state = 6},
  [29] = {.lex_state = 1, .external_lex_state = 6},
  [30] = {.lex_state = 1, .external_lex_state = 5},
  [31] = {.lex_state = 1, .external_lex_state = 8},
  [32] = {.lex_state = 1, .external_lex_state = 9},
  [33] = {.lex_state = 1, .external_lex_state = 4},
  [34] = {.lex_state = 1, .external_lex_state = 3},
  [35] = {.lex_state = 1, .external_lex_state = 5},
  [36] = {.lex_state = 1, .external_lex_state = 4},
  [37] = {.lex_state = 1, .external_lex_state = 4},
  [38] = {.lex_state = 1, .external_lex_state = 5},
  [39] = {.lex_state = 1, .external_lex_state = 9},
  [40] = {.lex_state = 1, .external_lex_state = 5},
  [41] = {.lex_state = 1, .external_lex_state = 9},
  [42] = {.lex_state = 1, .external_lex_state = 9},
  [43] = {.lex_state = 1, .external_lex_state = 4},
  [44] = {.lex_state = 1, .external_lex_state = 9},
  [45] = {.lex_state = 1, .external_lex_state = 9},
  [46] = {.lex_state = 1, .external_lex_state = 4},
  [47] = {.lex_state = 1, .external_lex_state = 4},
  [48] = {.lex_state = 1, .external_lex_state = 4},
  [49] = {.lex_state = 1, .external_lex_state = 4},
  [50] = {.lex_state = 1, .external_lex_state = 4},
  [51] = {.lex_state = 1, .external_lex_state = 4},
  [52] = {.lex_state = 1, .external_lex_state = 6},
  [53] = {.lex_state = 1, .external_lex_state = 6},
  [54] = {.lex_state = 1, .external_lex_state = 6},
  [55] = {.lex_state = 1, .external_lex_state = 6},
  [56] = {.lex_state = 1, .external_lex_state = 6},
  [57] = {.lex_state = 1, .external_lex_state = 4},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0, .external_lex_state = 10},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0, .external_lex_state = 10},
};

enum {
  ts_external_token_last_token_non_word = 0,
  ts_external_token_last_token_word = 1,
  ts_external_token_strong_open = 2,
  ts_external_token_strong_close = 3,
  ts_external_token_heading_prefix = 4,
  ts_external_token_equalsigns = 5,
  ts_external_token___error_canary = 6,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_last_token_non_word] = sym_last_token_non_word,
  [ts_external_token_last_token_word] = sym_last_token_word,
  [ts_external_token_strong_open] = sym_strong_open,
  [ts_external_token_strong_close] = sym_strong_close,
  [ts_external_token_heading_prefix] = sym_heading_prefix,
  [ts_external_token_equalsigns] = sym_equalsigns,
  [ts_external_token___error_canary] = sym___error_canary,
};

static const bool ts_external_scanner_states[11][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_last_token_non_word] = true,
    [ts_external_token_last_token_word] = true,
    [ts_external_token_strong_open] = true,
    [ts_external_token_strong_close] = true,
    [ts_external_token_heading_prefix] = true,
    [ts_external_token_equalsigns] = true,
    [ts_external_token___error_canary] = true,
  },
  [2] = {
    [ts_external_token_last_token_non_word] = true,
    [ts_external_token_strong_open] = true,
    [ts_external_token_heading_prefix] = true,
    [ts_external_token_equalsigns] = true,
  },
  [3] = {
    [ts_external_token_strong_open] = true,
    [ts_external_token_heading_prefix] = true,
    [ts_external_token_equalsigns] = true,
  },
  [4] = {
    [ts_external_token_strong_open] = true,
    [ts_external_token_equalsigns] = true,
  },
  [5] = {
    [ts_external_token_last_token_non_word] = true,
    [ts_external_token_strong_close] = true,
    [ts_external_token_equalsigns] = true,
  },
  [6] = {
    [ts_external_token_strong_close] = true,
    [ts_external_token_equalsigns] = true,
  },
  [7] = {
    [ts_external_token_last_token_word] = true,
    [ts_external_token_strong_open] = true,
    [ts_external_token_equalsigns] = true,
  },
  [8] = {
    [ts_external_token_last_token_word] = true,
    [ts_external_token_strong_close] = true,
    [ts_external_token_equalsigns] = true,
  },
  [9] = {
    [ts_external_token_last_token_non_word] = true,
    [ts_external_token_strong_open] = true,
    [ts_external_token_equalsigns] = true,
  },
  [10] = {
    [ts_external_token_strong_close] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(1),
    [aux_sym_newline_token1] = ACTIONS(1),
    [aux_sym_whitespace_token1] = ACTIONS(1),
    [aux_sym_word_token1] = ACTIONS(1),
    [aux_sym_special_token1] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_last_token_non_word] = ACTIONS(1),
    [sym_last_token_word] = ACTIONS(1),
    [sym_strong_open] = ACTIONS(1),
    [sym_strong_close] = ACTIONS(1),
    [sym_heading_prefix] = ACTIONS(1),
    [sym_equalsigns] = ACTIONS(1),
    [sym___error_canary] = ACTIONS(1),
  },
  [1] = {
    [sym_markup_block] = STATE(62),
    [sym__markup_content] = STATE(3),
    [sym_markup_leading_whitespace] = STATE(6),
    [sym_newline] = STATE(3),
    [sym_whitespace] = STATE(12),
    [sym_word] = STATE(12),
    [sym_special] = STATE(12),
    [sym_star] = STATE(12),
    [sym_strong] = STATE(12),
    [sym_heading] = STATE(3),
    [sym_line] = STATE(3),
    [sym_line_content] = STATE(60),
    [aux_sym_markup_block_repeat1] = STATE(3),
    [aux_sym_markup_leading_whitespace_repeat1] = STATE(16),
    [aux_sym_whitespace_repeat1] = STATE(24),
    [aux_sym_special_repeat1] = STATE(33),
    [aux_sym_heading_content_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(5),
    [aux_sym_newline_token1] = ACTIONS(7),
    [aux_sym_whitespace_token1] = ACTIONS(9),
    [aux_sym_word_token1] = ACTIONS(11),
    [aux_sym_special_token1] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [sym_last_token_non_word] = ACTIONS(17),
    [sym_strong_open] = ACTIONS(19),
    [sym_heading_prefix] = ACTIONS(21),
    [sym_equalsigns] = ACTIONS(23),
  },
  [2] = {
    [sym__markup_content] = STATE(4),
    [sym_markup_leading_whitespace] = STATE(6),
    [sym_newline] = STATE(4),
    [sym_whitespace] = STATE(12),
    [sym_word] = STATE(12),
    [sym_special] = STATE(12),
    [sym_star] = STATE(12),
    [sym_strong] = STATE(12),
    [sym_heading] = STATE(4),
    [sym_line] = STATE(4),
    [sym_line_content] = STATE(60),
    [aux_sym_markup_block_repeat1] = STATE(4),
    [aux_sym_markup_leading_whitespace_repeat1] = STATE(16),
    [aux_sym_whitespace_repeat1] = STATE(24),
    [aux_sym_special_repeat1] = STATE(33),
    [aux_sym_heading_content_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(25),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(5),
    [aux_sym_newline_token1] = ACTIONS(7),
    [aux_sym_whitespace_token1] = ACTIONS(9),
    [aux_sym_word_token1] = ACTIONS(11),
    [aux_sym_special_token1] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [sym_strong_open] = ACTIONS(19),
    [sym_heading_prefix] = ACTIONS(21),
    [sym_equalsigns] = ACTIONS(23),
  },
  [3] = {
    [sym__markup_content] = STATE(4),
    [sym_markup_leading_whitespace] = STATE(6),
    [sym_newline] = STATE(4),
    [sym_whitespace] = STATE(12),
    [sym_word] = STATE(12),
    [sym_special] = STATE(12),
    [sym_star] = STATE(12),
    [sym_strong] = STATE(12),
    [sym_heading] = STATE(4),
    [sym_line] = STATE(4),
    [sym_line_content] = STATE(60),
    [aux_sym_markup_block_repeat1] = STATE(4),
    [aux_sym_markup_leading_whitespace_repeat1] = STATE(16),
    [aux_sym_whitespace_repeat1] = STATE(24),
    [aux_sym_special_repeat1] = STATE(33),
    [aux_sym_heading_content_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(27),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(5),
    [aux_sym_newline_token1] = ACTIONS(7),
    [aux_sym_whitespace_token1] = ACTIONS(9),
    [aux_sym_word_token1] = ACTIONS(11),
    [aux_sym_special_token1] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [sym_strong_open] = ACTIONS(19),
    [sym_heading_prefix] = ACTIONS(21),
    [sym_equalsigns] = ACTIONS(23),
  },
  [4] = {
    [sym__markup_content] = STATE(4),
    [sym_markup_leading_whitespace] = STATE(6),
    [sym_newline] = STATE(4),
    [sym_whitespace] = STATE(12),
    [sym_word] = STATE(12),
    [sym_special] = STATE(12),
    [sym_star] = STATE(12),
    [sym_strong] = STATE(12),
    [sym_heading] = STATE(4),
    [sym_line] = STATE(4),
    [sym_line_content] = STATE(60),
    [aux_sym_markup_block_repeat1] = STATE(4),
    [aux_sym_markup_leading_whitespace_repeat1] = STATE(16),
    [aux_sym_whitespace_repeat1] = STATE(24),
    [aux_sym_special_repeat1] = STATE(33),
    [aux_sym_heading_content_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(29),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(31),
    [aux_sym_newline_token1] = ACTIONS(34),
    [aux_sym_whitespace_token1] = ACTIONS(37),
    [aux_sym_word_token1] = ACTIONS(40),
    [aux_sym_special_token1] = ACTIONS(43),
    [anon_sym_STAR] = ACTIONS(46),
    [sym_strong_open] = ACTIONS(49),
    [sym_heading_prefix] = ACTIONS(52),
    [sym_equalsigns] = ACTIONS(55),
  },
  [5] = {
    [sym__markup_content] = STATE(2),
    [sym_markup_leading_whitespace] = STATE(6),
    [sym_newline] = STATE(2),
    [sym_whitespace] = STATE(12),
    [sym_word] = STATE(12),
    [sym_special] = STATE(12),
    [sym_star] = STATE(12),
    [sym_strong] = STATE(12),
    [sym_heading] = STATE(2),
    [sym_line] = STATE(2),
    [sym_line_content] = STATE(60),
    [aux_sym_markup_block_repeat1] = STATE(2),
    [aux_sym_markup_leading_whitespace_repeat1] = STATE(16),
    [aux_sym_whitespace_repeat1] = STATE(24),
    [aux_sym_special_repeat1] = STATE(33),
    [aux_sym_heading_content_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(27),
    [aux_sym_markup_leading_whitespace_token1] = ACTIONS(5),
    [aux_sym_newline_token1] = ACTIONS(7),
    [aux_sym_whitespace_token1] = ACTIONS(9),
    [aux_sym_word_token1] = ACTIONS(11),
    [aux_sym_special_token1] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [sym_strong_open] = ACTIONS(19),
    [sym_heading_prefix] = ACTIONS(21),
    [sym_equalsigns] = ACTIONS(23),
  },
  [6] = {
    [sym_newline] = STATE(21),
    [sym_whitespace] = STATE(12),
    [sym_word] = STATE(12),
    [sym_special] = STATE(12),
    [sym_star] = STATE(12),
    [sym_strong] = STATE(12),
    [sym_heading] = STATE(21),
    [sym_line] = STATE(21),
    [sym_line_content] = STATE(60),
    [aux_sym_whitespace_repeat1] = STATE(24),
    [aux_sym_special_repeat1] = STATE(33),
    [aux_sym_heading_content_repeat1] = STATE(12),
    [aux_sym_newline_token1] = ACTIONS(7),
    [aux_sym_whitespace_token1] = ACTIONS(58),
    [aux_sym_word_token1] = ACTIONS(11),
    [aux_sym_special_token1] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(15),
    [sym_strong_open] = ACTIONS(19),
    [sym_heading_prefix] = ACTIONS(21),
    [sym_equalsigns] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(7), 1,
      aux_sym_newline_token1,
    ACTIONS(11), 1,
      aux_sym_word_token1,
    ACTIONS(13), 1,
      aux_sym_special_token1,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      sym_strong_open,
    ACTIONS(23), 1,
      sym_equalsigns,
    ACTIONS(58), 1,
      aux_sym_whitespace_token1,
    STATE(19), 1,
      sym_newline,
    STATE(24), 1,
      aux_sym_whitespace_repeat1,
    STATE(33), 1,
      aux_sym_special_repeat1,
    STATE(59), 1,
      sym_heading_content,
    STATE(13), 6,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_strong,
      aux_sym_heading_content_repeat1,
  [42] = 12,
    ACTIONS(60), 1,
      aux_sym_newline_token1,
    ACTIONS(62), 1,
      aux_sym_whitespace_token1,
    ACTIONS(64), 1,
      aux_sym_word_token1,
    ACTIONS(66), 1,
      aux_sym_special_token1,
    ACTIONS(68), 1,
      anon_sym_STAR,
    ACTIONS(70), 1,
      sym_last_token_non_word,
    ACTIONS(72), 1,
      sym_strong_close,
    ACTIONS(74), 1,
      sym_equalsigns,
    STATE(28), 1,
      aux_sym_special_repeat1,
    STATE(29), 1,
      aux_sym_whitespace_repeat1,
    STATE(63), 1,
      sym_strong_content,
    STATE(14), 6,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      aux_sym_strong_content_repeat1,
  [84] = 11,
    ACTIONS(60), 1,
      aux_sym_newline_token1,
    ACTIONS(62), 1,
      aux_sym_whitespace_token1,
    ACTIONS(64), 1,
      aux_sym_word_token1,
    ACTIONS(66), 1,
      aux_sym_special_token1,
    ACTIONS(68), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      sym_equalsigns,
    ACTIONS(76), 1,
      sym_strong_close,
    STATE(28), 1,
      aux_sym_special_repeat1,
    STATE(29), 1,
      aux_sym_whitespace_repeat1,
    STATE(61), 1,
      sym_strong_content,
    STATE(14), 6,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      aux_sym_strong_content_repeat1,
  [123] = 10,
    ACTIONS(78), 1,
      aux_sym_newline_token1,
    ACTIONS(81), 1,
      aux_sym_whitespace_token1,
    ACTIONS(84), 1,
      aux_sym_word_token1,
    ACTIONS(87), 1,
      aux_sym_special_token1,
    ACTIONS(90), 1,
      anon_sym_STAR,
    ACTIONS(93), 1,
      sym_strong_close,
    ACTIONS(95), 1,
      sym_equalsigns,
    STATE(28), 1,
      aux_sym_special_repeat1,
    STATE(29), 1,
      aux_sym_whitespace_repeat1,
    STATE(10), 6,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      aux_sym_strong_content_repeat1,
  [159] = 10,
    ACTIONS(98), 1,
      aux_sym_newline_token1,
    ACTIONS(100), 1,
      aux_sym_whitespace_token1,
    ACTIONS(103), 1,
      aux_sym_word_token1,
    ACTIONS(106), 1,
      aux_sym_special_token1,
    ACTIONS(109), 1,
      anon_sym_STAR,
    ACTIONS(112), 1,
      sym_strong_open,
    ACTIONS(115), 1,
      sym_equalsigns,
    STATE(24), 1,
      aux_sym_whitespace_repeat1,
    STATE(33), 1,
      aux_sym_special_repeat1,
    STATE(11), 6,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_strong,
      aux_sym_heading_content_repeat1,
  [195] = 10,
    ACTIONS(11), 1,
      aux_sym_word_token1,
    ACTIONS(13), 1,
      aux_sym_special_token1,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      sym_strong_open,
    ACTIONS(23), 1,
      sym_equalsigns,
    ACTIONS(58), 1,
      aux_sym_whitespace_token1,
    ACTIONS(118), 1,
      aux_sym_newline_token1,
    STATE(24), 1,
      aux_sym_whitespace_repeat1,
    STATE(33), 1,
      aux_sym_special_repeat1,
    STATE(11), 6,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_strong,
      aux_sym_heading_content_repeat1,
  [231] = 10,
    ACTIONS(11), 1,
      aux_sym_word_token1,
    ACTIONS(13), 1,
      aux_sym_special_token1,
    ACTIONS(15), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      sym_strong_open,
    ACTIONS(23), 1,
      sym_equalsigns,
    ACTIONS(58), 1,
      aux_sym_whitespace_token1,
    ACTIONS(120), 1,
      aux_sym_newline_token1,
    STATE(24), 1,
      aux_sym_whitespace_repeat1,
    STATE(33), 1,
      aux_sym_special_repeat1,
    STATE(11), 6,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      sym_strong,
      aux_sym_heading_content_repeat1,
  [267] = 10,
    ACTIONS(60), 1,
      aux_sym_newline_token1,
    ACTIONS(62), 1,
      aux_sym_whitespace_token1,
    ACTIONS(64), 1,
      aux_sym_word_token1,
    ACTIONS(66), 1,
      aux_sym_special_token1,
    ACTIONS(68), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      sym_equalsigns,
    ACTIONS(122), 1,
      sym_strong_close,
    STATE(28), 1,
      aux_sym_special_repeat1,
    STATE(29), 1,
      aux_sym_whitespace_repeat1,
    STATE(10), 6,
      sym_newline,
      sym_whitespace,
      sym_word,
      sym_special,
      sym_star,
      aux_sym_strong_content_repeat1,
  [303] = 4,
    ACTIONS(124), 1,
      aux_sym_markup_leading_whitespace_token1,
    STATE(15), 1,
      aux_sym_markup_leading_whitespace_repeat1,
    ACTIONS(129), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(127), 7,
      sym_last_token_non_word,
      sym_strong_open,
      sym_heading_prefix,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [323] = 5,
    ACTIONS(131), 1,
      aux_sym_markup_leading_whitespace_token1,
    ACTIONS(137), 1,
      sym_last_token_non_word,
    STATE(15), 1,
      aux_sym_markup_leading_whitespace_repeat1,
    ACTIONS(135), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(133), 6,
      sym_strong_open,
      sym_heading_prefix,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [345] = 3,
    ACTIONS(143), 1,
      sym_last_token_non_word,
    ACTIONS(141), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(139), 8,
      sym_strong_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [363] = 2,
    ACTIONS(147), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(145), 8,
      sym_strong_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [378] = 2,
    ACTIONS(151), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(149), 8,
      sym_strong_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [393] = 2,
    ACTIONS(155), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(153), 8,
      sym_strong_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [408] = 2,
    ACTIONS(159), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(157), 8,
      sym_strong_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [423] = 2,
    ACTIONS(163), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(161), 8,
      sym_strong_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [438] = 2,
    ACTIONS(167), 2,
      aux_sym_whitespace_token1,
      aux_sym_special_token1,
    ACTIONS(165), 8,
      sym_strong_open,
      sym_heading_prefix,
      sym_equalsigns,
      ts_builtin_sym_end,
      aux_sym_markup_leading_whitespace_token1,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [453] = 4,
    ACTIONS(58), 1,
      aux_sym_whitespace_token1,
    ACTIONS(171), 1,
      aux_sym_special_token1,
    STATE(36), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(169), 5,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [470] = 3,
    ACTIONS(175), 1,
      aux_sym_special_token1,
    ACTIONS(177), 1,
      sym_last_token_word,
    ACTIONS(173), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [485] = 4,
    ACTIONS(181), 1,
      aux_sym_special_token1,
    ACTIONS(184), 1,
      sym_equalsigns,
    STATE(26), 1,
      aux_sym_special_repeat1,
    ACTIONS(179), 5,
      sym_strong_close,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [502] = 4,
    ACTIONS(189), 1,
      aux_sym_whitespace_token1,
    ACTIONS(192), 1,
      aux_sym_special_token1,
    STATE(27), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(187), 5,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [519] = 4,
    ACTIONS(66), 1,
      aux_sym_special_token1,
    ACTIONS(74), 1,
      sym_equalsigns,
    STATE(26), 1,
      aux_sym_special_repeat1,
    ACTIONS(194), 5,
      sym_strong_close,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [536] = 4,
    ACTIONS(62), 1,
      aux_sym_whitespace_token1,
    ACTIONS(171), 1,
      aux_sym_special_token1,
    STATE(27), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(169), 5,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [553] = 3,
    ACTIONS(198), 1,
      aux_sym_special_token1,
    ACTIONS(200), 1,
      sym_last_token_non_word,
    ACTIONS(196), 6,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [568] = 3,
    ACTIONS(175), 1,
      aux_sym_special_token1,
    ACTIONS(202), 1,
      sym_last_token_word,
    ACTIONS(173), 6,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [583] = 3,
    ACTIONS(206), 1,
      aux_sym_special_token1,
    ACTIONS(208), 1,
      sym_last_token_non_word,
    ACTIONS(204), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [598] = 4,
    ACTIONS(13), 1,
      aux_sym_special_token1,
    ACTIONS(23), 1,
      sym_equalsigns,
    STATE(37), 1,
      aux_sym_special_repeat1,
    ACTIONS(194), 5,
      sym_strong_open,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [615] = 2,
    ACTIONS(212), 1,
      aux_sym_special_token1,
    ACTIONS(210), 7,
      sym_strong_open,
      sym_heading_prefix,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [628] = 3,
    ACTIONS(216), 1,
      aux_sym_special_token1,
    ACTIONS(218), 1,
      sym_last_token_non_word,
    ACTIONS(214), 6,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [643] = 4,
    ACTIONS(192), 1,
      aux_sym_special_token1,
    ACTIONS(220), 1,
      aux_sym_whitespace_token1,
    STATE(36), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(187), 5,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [660] = 4,
    ACTIONS(223), 1,
      aux_sym_special_token1,
    ACTIONS(226), 1,
      sym_equalsigns,
    STATE(37), 1,
      aux_sym_special_repeat1,
    ACTIONS(179), 5,
      sym_strong_open,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [677] = 3,
    ACTIONS(141), 1,
      aux_sym_special_token1,
    ACTIONS(229), 1,
      sym_last_token_non_word,
    ACTIONS(139), 6,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [692] = 3,
    ACTIONS(233), 1,
      aux_sym_special_token1,
    ACTIONS(235), 1,
      sym_last_token_non_word,
    ACTIONS(231), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [707] = 3,
    ACTIONS(239), 1,
      aux_sym_special_token1,
    ACTIONS(241), 1,
      sym_last_token_non_word,
    ACTIONS(237), 6,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [722] = 3,
    ACTIONS(239), 1,
      aux_sym_special_token1,
    ACTIONS(243), 1,
      sym_last_token_non_word,
    ACTIONS(237), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [737] = 3,
    ACTIONS(198), 1,
      aux_sym_special_token1,
    ACTIONS(245), 1,
      sym_last_token_non_word,
    ACTIONS(196), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [752] = 3,
    ACTIONS(249), 1,
      aux_sym_special_token1,
    STATE(36), 1,
      aux_sym_whitespace_repeat1,
    ACTIONS(247), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [767] = 3,
    ACTIONS(253), 1,
      aux_sym_special_token1,
    ACTIONS(255), 1,
      sym_last_token_non_word,
    ACTIONS(251), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [782] = 3,
    ACTIONS(216), 1,
      aux_sym_special_token1,
    ACTIONS(257), 1,
      sym_last_token_non_word,
    ACTIONS(214), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [797] = 2,
    ACTIONS(253), 1,
      aux_sym_special_token1,
    ACTIONS(251), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [809] = 2,
    ACTIONS(233), 1,
      aux_sym_special_token1,
    ACTIONS(231), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [821] = 2,
    ACTIONS(261), 1,
      aux_sym_special_token1,
    ACTIONS(259), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [833] = 2,
    ACTIONS(265), 1,
      aux_sym_special_token1,
    ACTIONS(263), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [845] = 2,
    ACTIONS(269), 1,
      aux_sym_special_token1,
    ACTIONS(267), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [857] = 2,
    ACTIONS(192), 1,
      aux_sym_special_token1,
    ACTIONS(187), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [869] = 2,
    ACTIONS(271), 1,
      aux_sym_special_token1,
    ACTIONS(179), 6,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [881] = 2,
    ACTIONS(163), 1,
      aux_sym_special_token1,
    ACTIONS(161), 6,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [893] = 2,
    ACTIONS(192), 1,
      aux_sym_special_token1,
    ACTIONS(187), 6,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [905] = 2,
    ACTIONS(269), 1,
      aux_sym_special_token1,
    ACTIONS(267), 6,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [917] = 2,
    ACTIONS(265), 1,
      aux_sym_special_token1,
    ACTIONS(263), 6,
      sym_strong_close,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [929] = 2,
    ACTIONS(271), 1,
      aux_sym_special_token1,
    ACTIONS(179), 6,
      sym_strong_open,
      sym_equalsigns,
      aux_sym_newline_token1,
      aux_sym_whitespace_token1,
      aux_sym_word_token1,
      anon_sym_STAR,
  [941] = 5,
    ACTIONS(7), 1,
      aux_sym_newline_token1,
    ACTIONS(58), 1,
      aux_sym_whitespace_token1,
    STATE(7), 1,
      sym_heading_whitespace,
    STATE(23), 1,
      sym_newline,
    STATE(43), 1,
      aux_sym_whitespace_repeat1,
  [957] = 2,
    ACTIONS(7), 1,
      aux_sym_newline_token1,
    STATE(18), 1,
      sym_newline,
  [964] = 2,
    ACTIONS(7), 1,
      aux_sym_newline_token1,
    STATE(20), 1,
      sym_newline,
  [971] = 1,
    ACTIONS(273), 1,
      sym_strong_close,
  [975] = 1,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
  [979] = 1,
    ACTIONS(76), 1,
      sym_strong_close,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 42,
  [SMALL_STATE(9)] = 84,
  [SMALL_STATE(10)] = 123,
  [SMALL_STATE(11)] = 159,
  [SMALL_STATE(12)] = 195,
  [SMALL_STATE(13)] = 231,
  [SMALL_STATE(14)] = 267,
  [SMALL_STATE(15)] = 303,
  [SMALL_STATE(16)] = 323,
  [SMALL_STATE(17)] = 345,
  [SMALL_STATE(18)] = 363,
  [SMALL_STATE(19)] = 378,
  [SMALL_STATE(20)] = 393,
  [SMALL_STATE(21)] = 408,
  [SMALL_STATE(22)] = 423,
  [SMALL_STATE(23)] = 438,
  [SMALL_STATE(24)] = 453,
  [SMALL_STATE(25)] = 470,
  [SMALL_STATE(26)] = 485,
  [SMALL_STATE(27)] = 502,
  [SMALL_STATE(28)] = 519,
  [SMALL_STATE(29)] = 536,
  [SMALL_STATE(30)] = 553,
  [SMALL_STATE(31)] = 568,
  [SMALL_STATE(32)] = 583,
  [SMALL_STATE(33)] = 598,
  [SMALL_STATE(34)] = 615,
  [SMALL_STATE(35)] = 628,
  [SMALL_STATE(36)] = 643,
  [SMALL_STATE(37)] = 660,
  [SMALL_STATE(38)] = 677,
  [SMALL_STATE(39)] = 692,
  [SMALL_STATE(40)] = 707,
  [SMALL_STATE(41)] = 722,
  [SMALL_STATE(42)] = 737,
  [SMALL_STATE(43)] = 752,
  [SMALL_STATE(44)] = 767,
  [SMALL_STATE(45)] = 782,
  [SMALL_STATE(46)] = 797,
  [SMALL_STATE(47)] = 809,
  [SMALL_STATE(48)] = 821,
  [SMALL_STATE(49)] = 833,
  [SMALL_STATE(50)] = 845,
  [SMALL_STATE(51)] = 857,
  [SMALL_STATE(52)] = 869,
  [SMALL_STATE(53)] = 881,
  [SMALL_STATE(54)] = 893,
  [SMALL_STATE(55)] = 905,
  [SMALL_STATE(56)] = 917,
  [SMALL_STATE(57)] = 929,
  [SMALL_STATE(58)] = 941,
  [SMALL_STATE(59)] = 957,
  [SMALL_STATE(60)] = 964,
  [SMALL_STATE(61)] = 971,
  [SMALL_STATE(62)] = 975,
  [SMALL_STATE(63)] = 979,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_block, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_block, 2),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_block, 1),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(16),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(17),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(45),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(25),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(41),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(42),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(8),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(58),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_block_repeat1, 2), SHIFT_REPEAT(41),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(38),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(35),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(31),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(40),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(30),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_strong_content_repeat1, 2), SHIFT_REPEAT(40),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(45),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(25),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(41),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(42),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(8),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_content_repeat1, 2), SHIFT_REPEAT(41),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_content, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_content, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong_content, 1),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_leading_whitespace_repeat1, 2), SHIFT_REPEAT(15),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_markup_leading_whitespace_repeat1, 2),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_markup_leading_whitespace_repeat1, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_leading_whitespace, 1),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_leading_whitespace, 1),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_newline, 1),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_newline, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 4),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 4),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line, 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__markup_content, 2),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__markup_content, 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_newline, 2),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_newline, 2),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 2),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 2),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_whitespace, 1),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_whitespace, 1),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_special_repeat1, 2),
  [181] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_special_repeat1, 2), SHIFT_REPEAT(40),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_special_repeat1, 2), SHIFT_REPEAT(40),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_whitespace_repeat1, 2),
  [189] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_whitespace_repeat1, 2), SHIFT_REPEAT(35),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_whitespace_repeat1, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special, 1),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_star, 1),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_star, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong, 2),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong, 2),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_leading_whitespace, 2),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_leading_whitespace, 2),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_whitespace_repeat1, 1),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_whitespace_repeat1, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_whitespace_repeat1, 2), SHIFT_REPEAT(45),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_special_repeat1, 2), SHIFT_REPEAT(41),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_special_repeat1, 2), SHIFT_REPEAT(41),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong, 3),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong, 3),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_special_repeat1, 1),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_special_repeat1, 1),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_whitespace, 1),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading_whitespace, 1),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong, 4),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong, 4),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_strong, 5),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_strong, 5),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_star, 2),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_star, 2),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_word, 2),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_word, 2),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_special_repeat1, 2),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [275] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_typst_external_scanner_create(void);
void tree_sitter_typst_external_scanner_destroy(void *);
bool tree_sitter_typst_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_typst_external_scanner_serialize(void *, char *);
void tree_sitter_typst_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_typst(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_typst_external_scanner_create,
      tree_sitter_typst_external_scanner_destroy,
      tree_sitter_typst_external_scanner_scan,
      tree_sitter_typst_external_scanner_serialize,
      tree_sitter_typst_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
